var cidadefuso = {
    "A Coruña": 4,
    "Aachen": 4,
    "Aalborg": 4,
    "Aalen": 4,
    "Aalst": 4,
    "Aarau": 4,
    "Aarhus": 4,
    "Abbotsford": 5,
    "Abéché": 4,
    "Abeokuta": 4,
    "Abidjan": 3,
    "Abilene": 3,
    "Abu Dhabi": 7,
    "Abuja": 4,
    "Acapulco": 3,
    "Accra": 3,
    "Aconibe": 4,
    "Adak": 7,
    "Adama": 6,
    "Adamstown": 5,
    "Addis Ababa": 6,
    "Adelaide": 13.5,
    "Aden": 6,
    "Adrar": 4,
    "Agadez": 4,
    "Agadir": 4,
    "Agra": 8.5,
    "Aguascalientes": 3,
    "Ahmedabad": 8.5,
    "Ahmedgarh": 8.5,
    "Akron": 2,
    "Akureyri": 3,
    "Al Jizah": 5,
    "Al-Fashir": 5,
    "Al-Ubayyid": 5,
    "Alajuela": 3,
    "Albany": 2,
    "Albufeira": 3,
    "Albuquerque": 4,
    "Alderney": 3,
    "Alert": 2,
    "Ålesund": 4,
    "Alexandria": 2,
    "Algiers": 4,
    "Ali Sabieh": 6,
    "Alicante": 4,
    "Alice Springs": 12.5,
    "Allentown": 2,
    "Almaty": 9,
    "Almería": 4,
    "Alofi": 8,
    "Altdorf": 4,
    "Amarillo": 3,
    "Ambato": 2,
    "Amman": 5,
    "Amsterdam": 4,
    "Amsterdam Island": 8,
    "Anadyr": 15,
    "Anaheim": 5,
    "Anantapur": 8.5,
    "Anchorage": 6,
    "Andorra La Vella": 4,
    "Angels Camp": 5,
    "Ankara": 6,
    "Ann Arbor": 2,
    "Annapolis": 2,
    "Anshan": 11,
    "Antananarivo": 6,
    "Antofagasta": 0,
    "Antsirabe": 6,
    "Antsiranana": 6,
    "Antwerp": 4,
    "Apia": 17,
    "Appenzell": 4,
    "Aqtobe": 8,
    "Arauca": 2,
    "Arawa": 14,
    "Arba Minch": 6,
    "Arequipa": 2,
    "Argostoli": 5,
    "Arkhangelsk": 6,
    "Arlington": 3,
    "Arlit": 4,
    "Arlon": 4,
    "Arnsberg": 4,
    "Arroyo": 1,
    "Artigas": 0,
    "Arusha": 6,
    "Aschaffenburg": 4,
    "Ashgabat": 8,
    "Asmara": 6,
    "Assab": 6,
    "Assisi": 4,
    "Astrakhan": 7,
    "Asuncion": 0,
    "Aswan": 5,
    "Asyut": 5,
    "Atafu": 16,
    "Atakpamé": 3,
    "Athens": 5,
    "Atlanta": 2,
    "Auckland": 16,
    "Augsburg": 4,
    "Augusta (US-GA)": 2,
    "Augusta (US-ME)": 2,
    "Aurora": 4,
    "Austin": 3,
    "Ávila": 4,
    "Awasa": 6,
    "Babruysk": 6,
    "Baden-Baden": 4,
    "Bafatá": 3,
    "Baghdad": 6,
    "Bahawalpur": 8,
    "Bahir Dar": 6,
    "Baker Island": 9,
    "Baker Lake": 3,
    "Bakersfield": 5,
    "Baku": 7,
    "Balikpapan": 11,
    "Balsas": 0,
    "Bălți": 5,
    "Baltimore": 2,
    "Bamako": 3,
    "Bambari": 4,
    "Bamenda": 4,
    "Bandar Seri Begawan": 11,
    "Bandung": 10,
    "Bangalore": 8.5,
    "Bangkok": 10,
    "Bangui": 4,
    "Banja Luka": 4,
    "Banjul": 3,
    "Bantam": 9.5,
    "Baotou": 11,
    "Baranovichi": 6,
    "Barcelona": 4,
    "Bardera": 6,
    "Barnaul": 10,
    "Barquisimeto": 1,
    "Barra do Garças": 0,
    "Barranquilla": 2,
    "Barrie": 2,
    "Barysaw": 6,
    "Basel": 4,
    "Basse-Terre": 1,
    "Basse-Terre (Guadeloupe)": 1,
    "Basseterre": 1,
    "Basseterre (St. Kitts)": 1,
    "Bastia": 4,
    "Bata": 4,
    "Baton Rouge": 3,
    "Batumi": 7,
    "Bayreuth": 4,
    "Beaumont": 3,
    "Béchar": 4,
    "Beijing": 11,
    "Beira": 5,
    "Beirut": 5,
    "Belém": 0,
    "Belfast": 3,
    "Belgrade": 4,
    "Belize City": 3,
    "Bellinzona": 4,
    "Belmopan": 3,
    "Belo Horizonte": 0,
    "Belushya Guba": 6,
    "Benghazi": 5,
    "Bengkulu": 10,
    "Benidorm": 4,
    "Benin City": 4,
    "Berbera": 6,
    "Berbérati": 4,
    "Bergamo": 4,
    "Bergen": 4,
    "Bergheim": 4,
    "Bergisch Gladbach": 4,
    "Berkeley": 5,
    "Berlin": 4,
    "Bern": 4,
    "Bertoua": 4,
    "Bethlehem": 5,
    "Bhubaneshwar": 8.5,
    "Biel": 4,
    "Bielefeld": 4,
    "Big Bend": 5,
    "Bijeljina": 4,
    "Billings": 4,
    "Bimbo": 4,
    "Birao": 4,
    "Birmingham": 3,
    "Bishkek": 9,
    "Bismarck": 3,
    "Bissau": 3,
    "Bitola": 4,
    "Bizerte": 4,
    "Blanc-Sablon": 1,
    "Blantyre": 5,
    "Bloemfontein": 5,
    "Bo": 3,
    "Boa Vista": 1,
    "Bobo-Dioulasso": 3,
    "Bocholt": 4,
    "Bochum": 4,
    "Bogota": 2,
    "Bohicon": 4,
    "Boise": 4,
    "Boké": 3,
    "Bologna": 4,
    "Bolzano": 4,
    "Bonn": 4,
    "Bordeaux": 4,
    "Borgarnes": 3,
    "Bosaso": 6,
    "Boston": 2,
    "Bottrop": 4,
    "Bouaké": 3,
    "Bowral": 14,
    "Bozoum": 4,
    "Brades": 1,
    "Brăila": 5,
    "Brampton": 2,
    "Brasilia": 0,
    "Brașov": 5,
    "Bratislava": 4,
    "Braunschweig": 4,
    "Brazzaville": 4,
    "Bregenz": 4,
    "Bremen": 4,
    "Bremerhaven": 4,
    "Brescia": 4,
    "Brest": 6,
    "Bria": 4,
    "Bridgeport": 2,
    "Bridgetown": 1,
    "Brisbane": 13,
    "Bristol": 3,
    "Brno": 4,
    "Brookings": 3,
    "Bruck an der Leitha": 4,
    "Brussels": 4,
    "Bryan – College Station": 3,
    "Bryansk": 6,
    "Bucaramanga": 2,
    "Bucharest": 5,
    "Buckeye": 4,
    "Budapest": 4,
    "Buenos Aires": 0,
    "Buffalo": 2,
    "Bujumbura": 5,
    "Buka": 14,
    "Bukavu": 5,
    "Bulawayo": 5,
    "Burgas": 5,
    "Burlington": 2,
    "Burnaby": 5,
    "Bursa": 6,
    "Busan": 12,
    "Butare": 5,
    "Cabinda": 4,
    "Cadiz": 4,
    "Cagliari": 4,
    "Caguas": 1,
    "Cahul": 5,
    "Cairns": 13,
    "Cairo": 5,
    "Calgary": 4,
    "Cali": 2,
    "Callao": 2,
    "Camagüey": 2,
    "Cambridge": 2,
    "Campinas": 0,
    "Canberra": 14,
    "Cancún": 2,
    "Canelones": 0,
    "Cannes": 4,
    "Cap-Haïtien": 2,
    "Cape Bojador": 4,
    "Cape Coral": 2,
    "Cape Town": 5,
    "Capri": 4,
    "Caracas": 1,
    "Carbondale": 3,
    "Cardiff": 3,
    "Carlini Base": 0,
    "Carson City": 5,
    "Cartagena": 2,
    "Casablanca": 4,
    "Cascais": 3,
    "Castries": 1,
    "Castrop-Rauxel": 4,
    "Cayenne": 0,
    "Cazin": 4,
    "Cedar Rapids": 3,
    "Celje": 4,
    "Celle": 4,
    "Ceuta": 4,
    "Chaguanas": 1,
    "Châlons-en-Champagne": 4,
    "Changchun": 11,
    "Changde": 11,
    "Changsha": 11,
    "Charleroi": 4,
    "Charleston (SC)": 2,
    "Charleston (WV)": 2,
    "Charlestown": 1,
    "Charlotte": 2,
    "Charlotte Amalie": 1,
    "Charlottetown": 1,
    "Chatham Islands": 16.75,
    "Chatham-Kent": 2,
    "Chattanooga": 2,
    "Cheboksary": 6,
    "Cheltenham": 3,
    "Chelyabinsk": 8,
    "Chemnitz": 4,
    "Chengdu": 11,
    "Chennai": 8.5,
    "Chernobyl": 5,
    "Chesapeake": 2,
    "Chetumal": 2,
    "Cheyenne": 4,
    "Chibougamau": 2,
    "Chicago": 3,
    "Chieti": 4,
    "Chihuahua": 4,
    "Chipata": 5,
    "Chișinău": 5,
    "Chita": 12,
    "Chittagong": 9,
    "Chitungwiza": 5,
    "Choloma": 3,
    "Chongqing": 11,
    "Christchurch": 16,
    "Christiansted": 1,
    "Chula Vista": 5,
    "Chur": 4,
    "Cincinnati": 2,
    "Citrus Heights": 5,
    "Ciudad Bolívar": 1,
    "Ciudad del Este": 0,
    "Ciudad Guayana": 1,
    "Ciudad Juárez": 4,
    "Ciudad Victoria": 3,
    "Clarksville": 3,
    "Cleveland": 2,
    "Cluj-Napoca": 5,
    "Cobija": 1,
    "Cochabamba": 1,
    "Cockburn Harbour": 2,
    "Cockburn Town": 2,
    "Codrington (Barbuda)": 1,
    "Colima": 3,
    "Cologne": 4,
    "Colombo": 8.5,
    "Colón": 2,
    "Colonia": 13,
    "Colonia del Sacramento": 0,
    "Columbia (us-mo)": 3,
    "Columbia (us-sc)": 2,
    "Columbus (US-GA)": 2,
    "Columbus (US-OH)": 2,
    "Conakry": 3,
    "Concepción de La Vega": 1,
    "Concord": 2,
    "Constantine": 4,
    "Copenhagen": 4,
    "Coquitlam": 5,
    "Coral Harbour": 2,
    "Córdoba": 4,
    "Cork": 3,
    "Cotonou": 4,
    "Cottbus": 4,
    "Craiova": 5,
    "Cranbrook": 4,
    "Criciúma": 0,
    "Cruz Bay": 1,
    "Cúcuta": 2,
    "Cuenca": 2,
    "Cuernavaca": 3,
    "Curitiba": 0,
    "Cuxhaven": 4,
    "Dabakala": 3,
    "Daegu": 12,
    "Dakar": 3,
    "Dakhla": 4,
    "Dalian": 11,
    "Dallas": 3,
    "Daloa": 3,
    "Damascus": 5,
    "Dangriga": 3,
    "Danmarkshavn": 3,
    "Dar es Salaam": 6,
    "Darmstadt": 4,
    "Darwin": 12.5,
    "Daugavpils": 5,
    "Davao": 11,
    "David": 2,
    "Dayton": 2,
    "Debre Berhan": 6,
    "Debrecen": 4,
    "Decatur": 3,
    "Delémont": 4,
    "Delhi": 8.5,
    "Delmenhorst": 4,
    "Denison": 3,
    "Denizli": 6,
    "Denpasar": 11,
    "Denver": 4,
    "Des Moines": 3,
    "Dessau-Rosslau": 4,
    "Dessie": 6,
    "Detmold": 4,
    "Detroit": 2,
    "Deutschlandsberg": 4,
    "Dhaka": 9,
    "Diego Garcia": 9,
    "Differdange": 4,
    "Dikhil": 6,
    "Dili": 12,
    "Dinslaken": 4,
    "Dire Dawa": 6,
    "Divo": 3,
    "Diyarbakır": 6,
    "Djibouti": 6,
    "Djougou": 4,
    "Dnipro": 5,
    "Dodoma": 6,
    "Doha": 6,
    "Dolisie": 4,
    "Donetsk": 6,
    "Dori": 3,
    "Dormagen": 4,
    "Dorra": 6,
    "Dorsten": 4,
    "Dortmund": 4,
    "Douala": 4,
    "Douglas": 3,
    "Dover": 2,
    "Drammen": 4,
    "Drogheda": 3,
    "Dubai": 7,
    "Dublin": 3,
    "Duisburg": 4,
    "Durango": 3,
    "Durazno": 0,
    "Durban": 5,
    "Düren": 4,
    "Durrës": 4,
    "Dushanbe": 8,
    "Düsseldorf": 4,
    "Easter Island": 2,
    "Ebebiyín": 4,
    "Ecatepec": 3,
    "Edinburgh": 3,
    "Edinburgh of the Seven Seas": 3,
    "Edmonton": 4,
    "Eferding": 4,
    "Eisenstadt": 4,
    "El Aaiún": 4,
    "El Jadida": 4,
    "El Monte": 5,
    "El Paso": 4,
    "Elbasan": 4,
    "Elista": 6,
    "Elizabeth": 2,
    "Emden": 4,
    "Encarnación": 0,
    "Entebbe": 6,
    "Enugu": 4,
    "Erfurt": 4,
    "Erie": 2,
    "Erlangen": 4,
    "Erzurum": 6,
    "Esch-sur-Alzette": 4,
    "Escondido": 5,
    "Escuintla": 3,
    "Eskişehir": 6,
    "Esmeraldas": 2,
    "Esperanza Base": 0,
    "Espoo": 5,
    "Essen": 4,
    "Esslingen": 4,
    "Ettelbruck": 4,
    "Eucla": 11.75,
    "Eugene": 5,
    "Eureka": 3,
    "Euskirchen": 4,
    "Evansville": 3,
    "Fada": 4,
    "Fada N'gourma": 3,
    "Fairbanks": 6,
    "Faisalabad": 8,
    "Fakaofo": 16,
    "Farafenni": 3,
    "Fargo": 3,
    "Faya-Largeau": 4,
    "Fayetteville (NC)": 2,
    "Fayetteville (US-AR)": 3,
    "Feldbach": 4,
    "Ferizaj": 4,
    "Fernando de Noronha": 1,
    "Fes": 4,
    "Fianarantsoa": 6,
    "Flensburg": 4,
    "Flint": 2,
    "Florencia": 2,
    "Florida": 0,
    "Fomboni": 6,
    "Foochow": 11,
    "Fort Lauderdale": 2,
    "Fort Smith": 3,
    "Fort Wayne": 2,
    "Fort Worth": 3,
    "Fort-de-France": 1,
    "Fortaleza": 0,
    "Foshan": 11,
    "Foz do Iguaçu": 0,
    "Franceville": 4,
    "Francistown": 5,
    "Frankfort": 2,
    "Frankfurt": 4,
    "Frauenfeld": 4,
    "Fray Bentos": 0,
    "Freeport": 2,
    "Freetown": 3,
    "Freiburg": 4,
    "Freising": 4,
    "Freistadt": 4,
    "Fremont": 5,
    "Fresnillo": 3,
    "Fresno": 5,
    "Fribourg": 4,
    "Friedrichshafen": 4,
    "Fuerte Olimpo": 0,
    "Fukuoka": 12,
    "Fulda": 4,
    "Fullerton": 5,
    "Funafuti": 15,
    "Fürstenfeld": 4,
    "Fürth": 4,
    "Fushun": 11,
    "Gabès": 4,
    "Gaborone": 5,
    "Gabú": 3,
    "Gafsa": 4,
    "Gainesville": 2,
    "Galapagos Islands": 3,
    "Galkayo": 6,
    "Galway": 3,
    "Gambier Islands": 6,
    "Garbsen": 4,
    "Garissa": 6,
    "Garland": 3,
    "Garoua": 4,
    "Gatineau": 2,
    "Gavar": 7,
    "Gaza": 5,
    "Gbarnga": 3,
    "Gdańsk": 4,
    "Gelsenkirchen": 4,
    "General Santos": 11,
    "Geneva": 4,
    "Genoa": 4,
    "George": 5,
    "George Town": 2,
    "George Town (Bahamas)": 2,
    "George Town (Cayman)": 2,
    "Georgetown": 1,
    "Georgetown (Ascension Island)": 3,
    "Gera": 4,
    "Ghanzi": 5,
    "Ghardaïa": 4,
    "Ghent": 4,
    "Gibraltar": 4,
    "Giessen": 4,
    "Gijón": 4,
    "Gitarama": 5,
    "Gitega": 5,
    "Gizo": 14,
    "Gjakova": 4,
    "Gjirokastër": 4,
    "Gladbeck": 4,
    "Glarus": 4,
    "Glasgow": 3,
    "Glendale (USA-AZ)": 4,
    "Glendale (USA-CA)": 5,
    "Gmünd": 4,
    "Goiânia": 0,
    "Goma": 5,
    "Gomel": 6,
    "Gonaïves": 2,
    "Gondar": 6,
    "Goodyear": 4,
    "Göppingen": 4,
    "Görlitz": 4,
    "Gorontalo": 11,
    "Gothenburg": 4,
    "Göttingen": 4,
    "Grahamstown": 5,
    "Granada": 4,
    "Grand Rapids": 2,
    "Graz": 4,
    "Greater Sudbury": 2,
    "Greifswald": 4,
    "Grevenbroich": 4,
    "Grieskirchen": 4,
    "Grise Fiord": 2,
    "Grodno": 6,
    "Groningen": 4,
    "Grozny": 6,
    "Guadalajara": 3,
    "Gualeguaychú": 0,
    "Guangzhou": 11,
    "Guarulhos": 0,
    "Guatemala City": 3,
    "Guayaquil": 2,
    "Guelph": 2,
    "Guiyang": 11,
    "Gujranwala": 8,
    "Gulbene": 5,
    "Gulu": 6,
    "Gustavia": 1,
    "Gütersloh": 4,
    "Gweru": 5,
    "Gyumri": 7,
    "Hafizabad": 8,
    "Hagåtña": 13,
    "Hagen": 4,
    "Hai Phong": 10,
    "Halifax": 1,
    "Halle": 4,
    "Hamamatsu": 12,
    "Hamburg": 4,
    "Hameln": 4,
    "Hamilton": 1,
    "Hamilton (Bermuda)": 1,
    "Hamilton (CA-ON)": 2,
    "Hamm": 4,
    "Hammamet": 4,
    "Hampton": 2,
    "Hanau": 4,
    "Hangzhou": 11,
    "Hannover": 4,
    "Hanoi": 10,
    "Happy Valley-Goose Bay": 1,
    "Harare": 5,
    "Harbin": 11,
    "Hargeisa": 6,
    "Harper": 3,
    "Harrisburg": 2,
    "Hartford": 2,
    "Haugesund": 4,
    "Havana": 2,
    "Hayward": 5,
    "Heidelberg": 4,
    "Heilbronn": 4,
    "Helena": 4,
    "Helsinki": 5,
    "Herford": 4,
    "Herisau": 4,
    "Hermosillo": 4,
    "Herne": 4,
    "Herning": 4,
    "Herten": 4,
    "Hesperia": 5,
    "Hialeah": 2,
    "Hildesheim": 4,
    "Hillsboro": 5,
    "Hilo": 7,
    "Himeji": 12,
    "Hiroshima": 12,
    "Ho Chi Minh": 10,
    "Hobart": 14,
    "Höfn": 3,
    "Holguín": 2,
    "Hollywood (US-CA)": 5,
    "Hollywood (US-FL)": 2,
    "Hong Kong": 11,
    "Honiara": 14,
    "Honolulu": 7,
    "Houmt Souk (Djerba)": 4,
    "Houston": 3,
    "Hovd": 10,
    "Howland Island": 9,
    "Hradec Králové": 4,
    "Huambo": 4,
    "Huelva": 4,
    "Hugh Town": 3,
    "Humenné": 4,
    "Huntington Beach": 5,
    "Huntsville": 3,
    "Hurghada": 5,
    "Hürth": 4,
    "Hyderabad": 8.5,
    "Iași": 5,
    "Ibadan": 4,
    "Ibarra": 2,
    "Ibiza": 4,
    "Imperatriz": 0,
    "Impfondo": 4,
    "In Salah": 4,
    "Incheon": 12,
    "Independence": 3,
    "Indianapolis": 2,
    "Indore": 8.5,
    "Inglewood": 5,
    "Ingolstadt": 4,
    "Inírida": 2,
    "Innsbruck": 4,
    "Inuvik": 4,
    "Ioannina": 5,
    "Iqaluit": 2,
    "Iquitos": 2,
    "Iráklion": 5,
    "Irkutsk": 11,
    "Irvine": 5,
    "Irving": 3,
    "Iserlohn": 4,
    "Islamabad": 8,
    "Istanbul": 6,
    "Ittoqqortoormiit": 2,
    "Izhevsk": 7,
    "Izmir": 6,
    "Jackson": 3,
    "Jacksonville": 2,
    "Jaén": 4,
    "Jaipur": 8.5,
    "Jakarta": 10,
    "Jalingo": 4,
    "Jamestown": 3,
    "Jayapura": 12,
    "Jeddah": 6,
    "Jefferson City": 3,
    "Jelgava": 5,
    "Jena": 4,
    "Jersey City": 2,
    "Jerusalem": 5,
    "Jilin": 11,
    "Jimma": 6,
    "Jinan": 11,
    "Jinzhou": 11,
    "Joensuu": 5,
    "Johannesburg": 5,
    "Joplin": 3,
    "Juba": 6,
    "Juneau": 6,
    "Kabul": 7.5,
    "Kabwe": 5,
    "Kaduna": 4,
    "Kaga-Bandoro": 4,
    "Kagoshima": 12,
    "Kairouan": 4,
    "Kaiserslautern": 4,
    "Kakata": 3,
    "Kaliningrad": 5,
    "Kamloops": 5,
    "Kampala": 6,
    "Kandi": 4,
    "Kangerlussuaq": 0,
    "Kano": 4,
    "Kãnpur": 8.5,
    "Kansas City": 3,
    "Kansas City (US-KS)": 3,
    "Kansas City (US-MO)": 3,
    "Kanton Island": 16,
    "Kanye": 5,
    "Kapan": 7,
    "Kaposvár": 4,
    "Kara": 3,
    "Karachi": 8,
    "Karonga": 5,
    "Kasama": 5,
    "Kassala": 5,
    "Kassel": 4,
    "Kasserine": 4,
    "Kathmandu": 8.75,
    "Kaunas": 5,
    "Kawasaki": 12,
    "Kazan": 6,
    "Kecskemét": 4,
    "Keflavík": 3,
    "Kelowna": 5,
    "Kemi": 5,
    "Kempten": 4,
    "Kendari": 11,
    "Kenema": 3,
    "Keren": 6,
    "Kerpen": 4,
    "Key West": 2,
    "Kharga Oasis": 5,
    "Kharkiv": 5,
    "Khartoum": 5,
    "Khatanga": 10,
    "Kherson": 5,
    "Khmelnytskyi": 5,
    "Khon Kaen": 10,
    "Kiama": 14,
    "Kiel": 4,
    "Kigali": 5,
    "Kilkenny": 3,
    "Kindia": 3,
    "King Edward Point": 1,
    "Kingston": 2,
    "Kingston (Canada)": 2,
    "Kingston (Jm)": 2,
    "Kingston": 15,
    "Kingstown": 1,
    "Kinshasa": 4,
    "Kiritimati": 17,
    "Kiruna": 4,
    "Kisangani": 5,
    "Kismayo": 6,
    "Kisumu": 6,
    "Kitakyushu": 12,
    "Kitchener": 2,
    "Kitwe": 5,
    "Klagenfurt": 4,
    "Klaipėda": 5,
    "Klaksvík": 3,
    "Knoxville": 2,
    "Kobe": 12,
    "Koblenz": 4,
    "Kohtla-Järve": 5,
    "Koidu": 3,
    "Kolkata": 8.5,
    "Kolonia": 14,
    "Komsomolsk-on-Amur": 13,
    "Köniz": 4,
    "Konstanz": 4,
    "Korçë": 4,
    "Korhogo": 3,
    "Koror": 12,
    "Košice": 4,
    "Kosti": 5,
    "Koudougou": 3,
    "Koutiala": 3,
    "Kowloon": 11,
    "Kragujevac": 4,
    "Kraków": 4,
    "Kralendijk": 1,
    "Kranj": 4,
    "Krasnoyarsk": 10,
    "Krefeld": 4,
    "Kryvyi Rih": 5,
    "Kuala Lumpur": 11,
    "Kufra": 5,
    "Kumamoto": 12,
    "Kumanovo": 4,
    "Kumasi": 3,
    "Kunming": 11,
    "Kuressaare": 5,
    "Kutaisi": 7,
    "Kuujjuaq": 2,
    "Kuwait City": 6,
    "Kwajalein": 15,
    "Kyiv": 5,
    "Kyoto": 12,
    "Kyrenia": 5,
    "L'viv": 5,
    "La Ceiba": 3,
    "La Paz": 1,
    "La Plata": 0,
    "La Romana": 1,
    "Labadee": 2,
    "Labasa": 15,
    "Lae": 13,
    "Lagos": 4,
    "Lahore": 8,
    "Lakewood": 4,
    "Lalibela": 6,
    "Lambaréné": 4,
    "Lanchow": 11,
    "Langenfeld (Rheinland)": 4,
    "Lansing": 2,
    "Laredo": 3,
    "Larnaca": 5,
    "Larvik": 4,
    "Las Palmas (ES-Canary)": 3,
    "Las Vegas": 5,
    "Lausanne": 4,
    "Lautoka": 15,
    "Laval": 2,
    "Leeds": 3,
    "Leipzig": 4,
    "Leon": 3,
    "León": 3,
    "Leshan": 11,
    "Letterkenny": 3,
    "Leverkusen": 4,
    "Levuka": 15,
    "Lexington-Fayette": 2,
    "Lhasa": 11,
    "Liberec": 4,
    "Liberia": 3,
    "Libreville": 4,
    "Liepāja": 5,
    "Liestal": 4,
    "Lilongwe": 5,
    "Lima": 2,
    "Limassol": 5,
    "Limerick": 3,
    "Limón": 3,
    "Lincoln": 3,
    "Linden": 1,
    "Linz": 4,
    "Lipetsk": 6,
    "Lippstadt": 4,
    "Lira": 6,
    "Lisbon": 3,
    "Little Rock": 3,
    "Liverpool": 3,
    "Livno": 4,
    "Livonia": 2,
    "Ljubljana": 4,
    "Lobatse": 5,
    "Lódz": 4,
    "Loja": 2,
    "Lomé": 3,
    "London": 3,
    "Londonderry": 3,
    "Long Beach": 5,
    "Longueuil": 2,
    "Longyearbyen": 4,
    "Lord Howe Island": 14,
    "Los Angeles": 5,
    "Los Llanos de Aridane": 3,
    "Louisville": 2,
    "Loures": 3,
    "Lowell": 2,
    "Luanda": 4,
    "Lubango": 4,
    "Lübeck": 4,
    "Lubumbashi": 5,
    "Lucapa": 4,
    "Lucerne": 4,
    "Lucknow": 8.5,
    "Lüdenscheid": 4,
    "Ludhiana": 8.5,
    "Ludwigsburg": 4,
    "Ludwigshafen": 4,
    "Luena": 4,
    "Lugano": 4,
    "Luganville": 14,
    "Luhansk": 6,
    "Lünen": 4,
    "Luoyang": 11,
    "Lusaka": 5,
    "Luxembourg": 4,
    "Luxor": 5,
    "Lynchburg": 2,
    "Lyon": 4,
    "Maceió": 0,
    "Machu Picchu Pueblo": 2,
    "Macon": 2,
    "Madison": 3,
    "Madrid": 4,
    "Madurai": 8.5,
    "Mafeteng": 5,
    "Magadan": 14,
    "Magdeburg": 4,
    "Magnitogorsk": 8,
    "Mahajanga": 6,
    "Maiduguri": 4,
    "Mainz": 4,
    "Majuro": 15,
    "Makassar": 11,
    "Makeni": 3,
    "Makhachkala": 6,
    "Makkah": 6,
    "Makurdi": 4,
    "Malabo": 4,
    "Malakal": 6,
    "Malang": 10,
    "Malanje": 4,
    "Malatya": 6,
    "Maldonado": 0,
    "Male": 8,
    "Malmö": 4,
    "Mamoutzou": 6,
    "Man": 3,
    "Manado": 11,
    "Managua": 3,
    "Manama": 6,
    "Manaus": 1,
    "Manchester": 3,
    "Mandalay": 9.5,
    "Mango": 3,
    "Manila": 11,
    "Manitowoc": 3,
    "Manizales": 2,
    "Mannheim": 4,
    "Manokwari": 12,
    "Manzini": 5,
    "Maputo": 5,
    "Mar del Plata": 0,
    "Maracaibo": 1,
    "Maracay": 1,
    "Maradi": 4,
    "Marambio Base": 0,
    "Marburg": 4,
    "Maribor": 4,
    "Marigot": 1,
    "Marion Island (Prince Edward Islands)": 6,
    "Markham": 2,
    "Marl": 4,
    "Maroua": 4,
    "Marrakech": 4,
    "Marseille": 4,
    "Mary's Harbour": -0.5,
    "Masaya": 3,
    "Maseru": 5,
    "Masvingo": 5,
    "Mata-Utu": 15,
    "Matagalpa": 3,
    "Matamoros": 3,
    "Matsuyama": 12,
    "Maturín": 1,
    "Maun": 5,
    "May Pen": 2,
    "Mayagüez": 1,
    "Mazatlan": 4,
    "Mbabane": 5,
    "Mbale": 6,
    "Mbandaka": 4,
    "Mbarara": 6,
    "Mbeya": 6,
    "Mbuji-Mayi": 5,
    "McKinney": 3,
    "Medan": 10,
    "Medellin": 2,
    "Medina": 6,
    "Mek'ele": 6,
    "Melbourne": 14,
    "Melekeok": 12,
    "Melilla": 4,
    "Melo": 0,
    "Memphis": 3,
    "Mendefera": 6,
    "Mendoza": 0,
    "Menongue": 4,
    "Mercedes": 0,
    "Merida": 3,
    "Mersa Matruh": 5,
    "Mesa": 4,
    "Mesquite": 3,
    "Metairie": 3,
    "Mexicali": 5,
    "Mexico City": 3,
    "Miami": 2,
    "Midland": 3,
    "Midway": 8,
    "Milan": 4,
    "Milwaukee": 3,
    "Minas": 0,
    "Mindelo": 2,
    "Minden": 4,
    "Minneapolis": 3,
    "Minsk": 6,
    "Miskolc": 4,
    "Misrata": 5,
    "Mississauga": 2,
    "Mitú": 2,
    "Mobile": 3,
    "Modena": 4,
    "Modesto": 5,
    "Moers": 4,
    "Mogadishu": 6,
    "Mogilev": 6,
    "Molepolole": 5,
    "Mombasa": 6,
    "Monaco": 4,
    "Monastir": 4,
    "Mönchengladbach": 4,
    "Mongo": 4,
    "Mongu": 5,
    "Monrovia": 3,
    "Montego Bay": 2,
    "Montería": 2,
    "Monterrey": 3,
    "Montevideo": 0,
    "Montgomery": 3,
    "Montpelier": 2,
    "Montréal": 2,
    "Montreux": 4,
    "Monza": 4,
    "Moreno Valley": 5,
    "Moroni": 6,
    "Moscow": 6,
    "Mostar": 4,
    "Moundou": 4,
    "Mount Hagen": 13,
    "Moussoro": 4,
    "Mpulungu": 5,
    "Mudanjiang": 11,
    "Mülheim": 4,
    "Mülheim / Ruhr": 4,
    "Multan": 8,
    "Mumbai": 8.5,
    "Munich": 4,
    "Münster": 4,
    "Murmansk": 6,
    "Muscat": 7,
    "Mutare": 5,
    "Mutsamudu": 6,
    "Muyinga": 5,
    "Mwanza": 6,
    "Mzuzu": 5,
    "N'Djamena": 4,
    "Nadi": 15,
    "Næstved": 4,
    "Nagoya": 12,
    "Nãgpur": 8.5,
    "Nairobi": 6,
    "Nakuru": 6,
    "Nampula": 5,
    "Nanaimo": 5,
    "Nanchang": 11,
    "Nanjing": 11,
    "Nanning": 11,
    "Nantes": 4,
    "Naples": 4,
    "Narva": 5,
    "Nashville": 3,
    "Nassau": 2,
    "Natal": 0,
    "Natitingou": 4,
    "Naypyidaw": 9.5,
    "Ndola": 5,
    "Neiafu": 16,
    "Nekemte": 6,
    "Nelspruit": 5,
    "Neubrandenburg": 4,
    "Neuchâtel": 4,
    "Neumünster": 4,
    "Neuquén": 0,
    "Neuss": 4,
    "Neustadt an der Weinstraße": 4,
    "Neuwied": 4,
    "New Amsterdam": 1,
    "New Delhi": 8.5,
    "New Haven": 2,
    "New Orleans": 3,
    "New York": 2,
    "Newark": 2,
    "Newport News": 2,
    "Ngaoundéré": 4,
    "Ngerulmud": 12,
    "Ngozi": 5,
    "Niamey": 4,
    "Nice": 4,
    "Nicosia": 5,
    "Nieuw Nickerie": 0,
    "Niigata": 12,
    "Nikšić": 4,
    "Niš": 4,
    "Niterói": 0,
    "Nizhny Novgorod": 6,
    "Nome": 6,
    "Norderstedt": 4,
    "Nordhorn": 4,
    "Norfolk": 2,
    "Norilsk": 10,
    "North Nicosia": 5,
    "Nouadhibou": 3,
    "Nouakchott": 3,
    "Noumea": 14,
    "Novgorod": 6,
    "Novi Sad": 4,
    "Novo Mesto": 4,
    "Novorossiysk": 6,
    "Novosibirsk": 10,
    "Nukualofa": 16,
    "Nuremberg": 4,
    "Nursultan": 9,
    "Nuuk": 0,
    "Nzérékoré": 3,
    "Oakland": 5,
    "Oakville": 2,
    "Oaxaca": 3,
    "Oberhausen": 4,
    "Obo": 4,
    "Obock": 6,
    "Oceanside": 5,
    "Odense": 4,
    "Odesa": 5,
    "Offenbach": 4,
    "Offenburg": 4,
    "Ogden": 4,
    "Ohrid": 4,
    "Oklahoma City": 3,
    "Olathe": 3,
    "Oldenburg": 4,
    "Olomouc": 4,
    "Olympia": 5,
    "Omagh": 3,
    "Omsk": 9,
    "Ontario": 5,
    "Opuwo": 5,
    "Oradea": 5,
    "Oral": 8,
    "Oran": 4,
    "Orange": 5,
    "Orange Walk Town": 3,
    "Oranjestad": 1,
    "Oranjestad (Aruba)": 1,
    "Oranjestad (St. Eust.)": 1,
    "Orillia": 2,
    "Orlando": 2,
    "Osaka": 12,
    "Oshawa": 2,
    "Osijek": 4,
    "Oslo": 4,
    "Osnabrück": 4,
    "Osogbo": 4,
    "Ostrava": 4,
    "Ottawa": 2,
    "Ouagadougou": 3,
    "Ouahigouya": 3,
    "Ouargla": 4,
    "Ouarzazate": 4,
    "Ouésso": 4,
    "Overland Park": 3,
    "Owensboro": 3,
    "Owerri": 4,
    "Oxford": 3,
    "Oxnard": 5,
    "Oyem": 4,
    "Paderborn": 4,
    "Pago Pago": 8,
    "Palangka Raya": 10,
    "Palembang": 10,
    "Palermo": 4,
    "Palikir": 14,
    "Palma (ES-Majorca)": 4,
    "Palmerston North": 16,
    "Palu": 11,
    "Pamplona": 4,
    "Panama": 2,
    "Pangai": 16,
    "Papeete": 7,
    "Paradise": 5,
    "Parakou": 4,
    "Paramaribo": 0,
    "Paris": 4,
    "Parma": 4,
    "Pasadena (USA-CA)": 5,
    "Pasadena (USA-TX)": 3,
    "Passau": 4,
    "Paterson": 2,
    "Patna": 8.5,
    "Patras": 5,
    "Paysandú": 0,
    "Pedro Juan Caballero": 0,
    "Peize": 4,
    "Pemba": 5,
    "Pensacola": 3,
    "Peoria": 3,
    "Pereira": 2,
    "Perm": 8,
    "Perth": 11,
    "Petropavlovsk-Kamchatsky": 15,
    "Petrópolis": 0,
    "Pevek": 15,
    "Pforzheim": 4,
    "Philadelphia": 2,
    "Philipsburg": 1,
    "Phnom Penh": 10,
    "Phoenix": 4,
    "Piatra Neamț": 5,
    "Pierre": 3,
    "Pinar del Río": 2,
    "Piraeus": 5,
    "Pirassununga": 0,
    "Pisa": 4,
    "Pittsburgh": 2,
    "Plano": 3,
    "Plauen": 4,
    "Playa del Carmen": 2,
    "Pleven": 5,
    "Pljevlja": 4,
    "Ploiești": 5,
    "Plovdiv": 5,
    "Plymouth": 3,
    "Plzen": 4,
    "Podgorica": 4,
    "Pointe-à-Pitre": 1,
    "Pointe-Noire": 4,
    "Poitiers": 4,
    "Polokwane": 5,
    "Polotsk": 6,
    "Pomona": 5,
    "Ponce": 1,
    "Pond Inlet": 2,
    "Ponta Delgada": 2,
    "Pontianak": 10,
    "Popayán": 2,
    "Poprad": 4,
    "Port Elizabeth": 5,
    "Port Harcourt": 4,
    "Port Louis": 7,
    "Port Mathurin (Rodrigues)": 7,
    "Port Moresby": 13,
    "Port of Spain": 1,
    "Port Said": 5,
    "Port Sudan": 5,
    "Port Vila": 14,
    "Port-au-Prince": 2,
    "Port-aux-Francais": 8,
    "Port-Gentil": 4,
    "Portland (Maine)": 2,
    "Portland (Oregon)": 5,
    "Porto": 3,
    "Porto Alegre": 0,
    "Porto Novo": 4,
    "Porto Velho": 1,
    "Portoviejo": 2,
    "Portsmouth": 2,
    "Potchefstroom": 5,
    "Potsdam": 4,
    "Poznan": 4,
    "Prague": 4,
    "Praia": 2,
    "Prešov": 4,
    "Pretoria": 5,
    "Prijedor": 4,
    "Prince George": 5,
    "Princeton": 3,
    "Pristina": 4,
    "Prizren": 4,
    "Providence": 2,
    "Providenciales": 2,
    "Provo": 4,
    "Puebla": 3,
    "Puerto Ayacucho": 1,
    "Puerto Cabezas": 3,
    "Puerto Plata": 1,
    "Puerto Vallarta": 3,
    "Pune": 8.5,
    "Punta Arenas": 0,
    "Punta Cana": 1,
    "Punta Gorda": 3,
    "Puyo": 2,
    "Pyatigorsk": 6,
    "Pyongyang": 12,
    "Qaanaaq": 0,
    "Qacha's Nek": 5,
    "Qingdao": 11,
    "Qiqihar": 11,
    "Québec": 2,
    "Queens": 2,
    "Querétaro": 3,
    "Quetzaltenango": 3,
    "Quezon": 11,
    "Quimper": 4,
    "Quito": 2,
    "Rabat": 4,
    "Rabaul": 13,
    "Raleigh": 2,
    "Ramsey": 3,
    "Rancho Cucamonga": 5,
    "Rapid City": 4,
    "Rarotonga": 7,
    "Rasht": 6.5,
    "Ratingen": 4,
    "Ravensburg": 4,
    "Rawaki": 16,
    "Rawalpindi": 8,
    "Rawson": 0,
    "Recife": 0,
    "Recklinghausen": 4,
    "Regensburg": 4,
    "Regina": 3,
    "Resolute Bay": 3,
    "Rethymno": 5,
    "Reutlingen": 4,
    "Reykjavik": 3,
    "Reynosa": 3,
    "Rheine": 4,
    "Riberalta": 1,
    "Richmond (CA-BC)": 5,
    "Richmond (US-VA)": 2,
    "Richmond Hill": 2,
    "Riga": 5,
    "Rijeka": 4,
    "Rimini": 4,
    "Rio Branco": 2,
    "Rio de Janeiro": 0,
    "Rivera": 0,
    "Riverside": 5,
    "Riyadh": 6,
    "Road Town": 1,
    "Rocha": 0,
    "Rochester": 2,
    "Rockford": 3,
    "Rome": 4,
    "Rosario": 0,
    "Roseau": 1,
    "Rosenheim": 4,
    "Rosso": 3,
    "Rostock": 4,
    "Rotterdam": 4,
    "Rovaniemi": 5,
    "Ruhengeri": 5,
    "Rundu": 5,
    "Rustavi": 7,
    "Rustenburg": 5,
    "Rutana": 5,
    "Ruyigi": 5,
    "Rwamagana": 5,
    "Ryazan": 6,
    "Saarbrücken": 4,
    "Sabha": 5,
    "Sacramento": 5,
    "Sagamihara": 12,
    "Saguenay": 2,
    "Sahuarita": 4,
    "Saint George's": 1,
    "Saint Helier": 3,
    "Saint John (CA - NB)": 1,
    "Saint John's": 1,
    "Saint Thomas": 1,
    "Saint-Denis": 7,
    "Saint-Laurent-du-Maroni": 0,
    "Saint-Louis": 3,
    "Saint-Paul": 7,
    "Saint-Petersburg": 6,
    "Saint-Pierre": 0,
    "Saipan": 13,
    "Salaberry-de-Valleyfield": 2,
    "Salamanca": 4,
    "Salelologa": 17,
    "Salem": 5,
    "Salerno": 4,
    "Salihorsk": 6,
    "Salinas": 5,
    "Salt Lake City": 4,
    "Salta": 0,
    "Salto": 0,
    "Salvador": 0,
    "Salzburg": 4,
    "Salzgitter": 4,
    "Samara": 7,
    "Samsun": 6,
    "San Antonio": 3,
    "San Bernardino": 5,
    "San Diego": 5,
    "San Fernando": 1,
    "San Fernando de Apure": 1,
    "San Francisco": 5,
    "San Ignacio de Velasco": 1,
    "San Jose": 3,
    "San Jose (CR)": 3,
    "San Jose (USA)": 5,
    "San José de Mayo": 0,
    "San Juan": 1,
    "San Juan de la Maguana": 1,
    "San Luis Potosi": 3,
    "San Marino": 4,
    "San Miguel": 3,
    "San Pedro": 3,
    "San Pédro": 3,
    "San Pedro Sula": 3,
    "San Salvador": 3,
    "San Sebastián de La Gomera": 3,
    "San Vicente": 3,
    "Sana": 6,
    "Sancti Spíritus": 2,
    "Sandefjord": 4,
    "Sandvika": 4,
    "Santa Ana (SV)": 3,
    "Santa Ana (US-CA)": 5,
    "Santa Barbara": 5,
    "Santa Clara": 2,
    "Santa Clarita": 5,
    "Santa Cruz": 1,
    "Santa Cruz de Tenerife": 3,
    "Santa Fe": 4,
    "Santa Maria": 2,
    "Santa María Huatulco": 3,
    "Santa Rosa": 5,
    "Santander": 4,
    "Santarém": 0,
    "Santiago": 0,
    "Santiago de Cuba": 2,
    "Santiago de los Caballeros": 1,
    "Santiago de Veraguas": 2,
    "Santo António (Príncipe)": 3,
    "Santo Domingo": 1,
    "Santos": 0,
    "São Félix do Xingu": 0,
    "São Paulo": 0,
    "São Tomé": 3,
    "Sapporo": 12,
    "Sarajevo": 4,
    "Sarh": 4,
    "Sarnen": 4,
    "Saskatoon": 3,
    "Sassari": 4,
    "Savé": 4,
    "Scarborough": 1,
    "Schaffhausen": 4,
    "Schwäbisch Gmünd": 4,
    "Schweinfurt": 4,
    "Schwerin": 4,
    "Schwyz": 4,
    "Scottsdale": 4,
    "Seattle": 5,
    "Semarang": 10,
    "Seoul": 12,
    "Serekunda": 3,
    "Serowe": 5,
    "Sérres": 5,
    "Sevastopol": 6,
    "Sfax": 4,
    "Shanghai": 11,
    "Shantou": 11,
    "Sharm el-Sheikh": 5,
    "Shenyang": 11,
    "Shenzhen": 11,
    "Sherbrooke": 2,
    "Shijiazhuang": 11,
    "Shizuoka": 12,
    "Shkodër": 4,
    "Shreveport": 3,
    "Šiauliai": 5,
    "Sibiu": 5,
    "Siegen": 4,
    "Sikasso": 3,
    "Sikeston": 3,
    "Simferopol": 6,
    "Simi Valley": 5,
    "Sincelejo": 2,
    "Sindelfingen": 4,
    "Singapore": 11,
    "Sion": 4,
    "Sioux Falls": 3,
    "Sisian": 7,
    "Siwa Oasis": 5,
    "Skopje": 4,
    "Slavonski Brod": 4,
    "Sligo": 3,
    "Smara": 4,
    "Smolensk": 6,
    "Sochi": 6,
    "Sofia": 5,
    "Sokodé": 3,
    "Sokoto": 4,
    "Solihull": 3,
    "Solingen": 4,
    "Solothurn": 4,
    "Sorrento": 4,
    "Sousse": 4,
    "South Bend": 2,
    "Spanish Town": 1,
    "Speyer": 4,
    "Split": 4,
    "Springfield (IL)": 3,
    "Springfield (MA)": 2,
    "Springfield (MO)": 3,
    "Squamish": 5,
    "Srednekolymsk": 14,
    "Sri Jayawardenepura Kotte": 8.5,
    "St. Catharines": 2,
    "St. Clair Shores": 2,
    "St. Gallen": 4,
    "St. John's": -0.5,
    "St. John's (CA - NF)": -0.5,
    "St. Joseph": 3,
    "St. Louis": 3,
    "St. Paul": 3,
    "St. Peter Port": 3,
    "St. Petersburg": 2,
    "St. Pölten": 4,
    "Stamford": 2,
    "Stanley": 0,
    "Stans": 4,
    "Stara Zagora": 5,
    "Stavanger": 4,
    "Stavropol": 6,
    "Stellenbosch": 5,
    "Sterling Heights": 2,
    "Stockholm": 4,
    "Stockton": 5,
    "Stolberg (Rheinland)": 4,
    "Stralsund": 4,
    "Strasbourg": 4,
    "Stuttgart": 4,
    "Subotica": 4,
    "Sucre": 1,
    "Suez": 5,
    "Sukhumi": 6,
    "Sumy": 5,
    "Sunnyvale": 5,
    "Surabaya": 10,
    "Surakarta": 10,
    "Surat": 8.5,
    "Surrey": 5,
    "Suva": 15,
    "Suzhou": 11,
    "Swakopmund": 5,
    "Sydney": 14,
    "Syktyvkar": 6,
    "Syracuse": 2,
    "Szczecin": 4,
    "Szeged": 4,
    "Tabiteuea": 15,
    "Tabora": 6,
    "Tacuarembó": 0,
    "Tadjoura": 6,
    "Taiohae": 5.5,
    "Taipei": 11,
    "Taiyuan": 11,
    "Tallahassee": 2,
    "Tallinn": 5,
    "Tamale": 3,
    "Tamanrasset": 4,
    "Tambacounda": 3,
    "Tampa": 2,
    "Tandil": 0,
    "Tangier": 4,
    "Tangshan": 11,
    "Tarawa": 15,
    "Târgu Mureş": 5,
    "Tartu": 5,
    "Tashkent": 8,
    "Tauranga": 16,
    "Tbilisi": 7,
    "Tchibanga": 4,
    "Tegucigalpa": 3,
    "Tehran": 6.5,
    "Tel Aviv": 5,
    "Tempe": 4,
    "Tennant Creek": 12.5,
    "Tepic": 4,
    "Ternopil": 5,
    "Teseney": 6,
    "Texcoco": 3,
    "Teyateyaneng": 5,
    "The Bottom": 1,
    "The Hague": 4,
    "The Valley": 1,
    "Thessaloniki": 5,
    "Thiès": 3,
    "Thimphu": 9,
    "Thiruvananthapuram": 8.5,
    "Thousand Oaks": 5,
    "Thule Air Base": 1,
    "Thunder Bay": 2,
    "Tianjin": 11,
    "Tidjikja": 3,
    "Tijuana": 5,
    "Tiksi": 12,
    "Timbuktu": 3,
    "Timișoara": 5,
    "Tindouf": 4,
    "Tirana": 4,
    "Tiraspol": 5,
    "Toamasina": 6,
    "Tobruk": 5,
    "Tokyo": 12,
    "Toledo": 2,
    "Toliara": 6,
    "Topeka": 3,
    "Toronto": 2,
    "Torrance": 5,
    "Tórshavn": 3,
    "Touba": 3,
    "Toulouse": 4,
    "Trabzon": 6,
    "Traralgon": 14,
    "Trenton": 2,
    "Trier": 4,
    "Trieste": 4,
    "Trinidad": 0,
    "Tripoli": 5,
    "Trois-Rivieres": 2,
    "Troisdorf": 4,
    "Tromsø": 4,
    "Trondheim": 4,
    "Trujillo": 2,
    "Tsabong": 5,
    "Tshikapa": 5,
    "Tskhinvali": 6,
    "Tübingen": 4,
    "Tucson": 4,
    "Tucumán": 0,
    "Tula": 6,
    "Tunis": 4,
    "Turin": 4,
    "Turlock": 5,
    "Tuxtla Gutierrez": 3,
    "Tuzla": 4,
    "Ufa": 8,
    "Uíge": 4,
    "Ulaanbaatar": 11,
    "Ulm": 4,
    "Unalaska": 6,
    "Unna": 4,
    "Uppsala": 4,
    "Ürümqi": 11,
    "Uster": 4,
    "Ústí nad Labem": 4,
    "Utrecht": 4,
    "Utsunomiya": 12,
    "Uyo": 4,
    "Uzhgorod": 5,
    "Vaduz": 4,
    "Vaitape (Bora Bora)": 7,
    "Valencia": 1,
    "Valladolid": 4,
    "Vallejo": 5,
    "Valletta": 4,
    "Valmiera": 5,
    "Valparaíso": 0,
    "Valverde": 3,
    "Vanadzor": 7,
    "Vancouver": 5,
    "Varanasi": 8.5,
    "Varna": 5,
    "Vatican City": 4,
    "Velbert": 4,
    "Venice": 4,
    "Ventspils": 5,
    "Veracruz": 3,
    "Verkhoyansk": 13,
    "Verona": 4,
    "Versailles": 4,
    "Vestmannaeyjar": 3,
    "Victoria": 5,
    "Victorville": 5,
    "Vidin": 5,
    "Vienna": 4,
    "Vientiane": 10,
    "Viersen": 4,
    "Vieux Fort": 1,
    "Vila Nova de Gaia": 3,
    "Villach": 4,
    "Villavicencio": 2,
    "Vilnius": 5,
    "Viña del Mar": 0,
    "Virginia Beach": 2,
    "Visakhapatnam": 8.5,
    "Visalia": 5,
    "Vitebsk": 6,
    "Vitória": 0,
    "Vladimir": 6,
    "Vladivostok": 13,
    "Vlorë": 4,
    "Waco": 3,
    "Wailuku": 7,
    "Wake Island": 15,
    "Waldorf": 2,
    "Walvis Bay": 5,
    "Warren": 2,
    "Warsaw": 4,
    "Washington DC": 2,
    "Waterbury": 2,
    "Waterford": 3,
    "Wau": 6,
    "Weimar": 4,
    "Wellington": 16,
    "Weno": 13,
    "Wesel": 4,
    "Whistler": 5,
    "Whitehorse": 5,
    "Wichita": 3,
    "Wiesbaden": 4,
    "Willemstad": 1,
    "Windhoek": 5,
    "Windsor": 2,
    "Winnipeg": 3,
    "Winston-Salem": 2,
    "Winterthur": 4,
    "Wismar": 4,
    "Witten": 4,
    "Woerden": 4,
    "Wolfsburg": 4,
    "Wollongong": 14,
    "Worcester": 2,
    "Worms": 4,
    "Wroclaw": 4,
    "Wuhan": 11,
    "Wuppertal": 4,
    "Würzburg": 4,
    "Xankendi": 7,
    "Xi'an": 11,
    "Xiamen": 11,
    "Xinyang": 11,
    "Yakutsk": 12,
    "Yambio": 6,
    "Yamoussoukro": 3,
    "Yangon": 9.5,
    "Yaoundé": 4,
    "Yaren": 15,
    "Yeghegnadzor": 7,
    "Yekaterinburg": 8,
    "Yellowknife": 4,
    "Yerevan": 7,
    "Yokohama": 12,
    "Yonkers": 2,
    "Yoshkar-Ola": 6,
    "Yuzhno-Sakhalinsk": 14,
    "Zacatecas": 3,
    "Zagazig": 5,
    "Zagreb": 4,
    "Zanzibar City": 6,
    "Zaporizhia": 5,
    "Zaria": 4,
    "Zarzis": 4,
    "Zenica": 4,
    "Zhengzhou": 11,
    "Zibo": 11,
    "Ziguinchor": 3,
    "Žilina": 4,
    "Zinder": 4,
    "Zug": 4,
    "Zürich": 4,
    "Zwickau": 4,
}